name: bse_2.14
channels:
  - defaults
dependencies:
  - numpy=1.26.4=py39h055cbcc_0
  - pandas=2.2.1=py39h5da7b33_0
  - scipy=1.12.0=py39h8640f81_0
  - tensorflow=2.10.0=mkl_py39ha510bab_0
  - pip=24.0
